### ISSUE TITLE
Annotating large strings is slow/incorrect

### ISSUE THREAD

**Issue by mattdahl** [freelawproject/eyecite#34]
Here's a gist: https://gist.github.com/mattdahl/21080e7aafd0a28c3ef0ebf9d9d13b0c

In short, when `use_dmp=True`, the annotation is inserted at the wrong location. When `use_dmp=False`, the location is correct, but it takes about 30 seconds to compute on my machine.

**Comment by mlissner** [comment]
Hm, sounds like it might be two bugs. Performance of the non-dmp approach and accuracy of the dmp library.

**Comment by jcushman** [comment]
Sorry, just saw this ...

I get correct results from `use_dmp=True` in your gist. Can you confirm that this doesn't work? If so maybe we'll have to check OS versions and such. 😬

```
from pathlib import Path
from eyecite import annotate, clean_text

opinion_text = Path('opinion_text.txt').read_text()
cleaned_text = clean_text(opinion_text, ["all_whitespace"])

result_dmp = annotate(
  plain_text=cleaned_text,
  annotations=[((902, 915), '~FOO~', '~BAR~')],
  source_text=opinion_text,
  use_dmp=True)

result_builtin = annotate(
  plain_text=cleaned_text,
  annotations=[((902, 915), '~FOO~', '~BAR~')],
  source_text=opinion_text,
  use_dmp=False)

print(result_dmp==result_builtin)
# True
```

(Both result in the annotation "~FOO~539\n  U. S. 306~BAR~").

I agree the performance of the builtin difflib is unacceptable, though! And the pure-python version of DMP isn't too fast either -- apparently it's [known to Google](https://github.com/google/diff-match-patch) to be hundreds of times slower than the C++ version. I can send a PR to use the faster DMP, and maybe we want that to be the default, assuming it's giving correct results.

**Comment by mattdahl** [comment]
No worries, I should have tagged you. Infuriatingly, however, now I can't reproduce my original gist either.

However, I modified the test string to be even longer than before (now it's a full opinion from CL), and I think now something similar is happening. Edited gist: https://gist.github.com/mattdahl/21080e7aafd0a28c3ef0ebf9d9d13b0c

The native library is still slow but correct, but the `diff_match_patch` now just (incorrectly) puts the annotation at the beginning of the string. I also added a third option -- the new `diff_match_patch_python` library in your #43 -- which seems to be both correct and fast to me.

I haven't attempted to debug this at all, but if the C++ version is fastest and seems to be working correctly, I see no reason to not just switch to that. However, I would be curious to know if you can reproduce the error in this version of the gist at least, to make sure I'm not doing something insane...

**Comment by jcushman** [comment]
Hmm, yeah, I can reproduce your second gist. For whatever reason the pure-python DMP is just throwing up its hands on that example and deciding that the entire file should be replaced:

```
from diff_match_patch import diff_match_patch
from eyecite import clean_text

b = Path("opinion_text.txt").read_text()
a = clean_text(opinion_text, ["all_whitespace"])

print(diff_match_patch().diff_main(a, b))
```

Prints:

```
[
  [
    0,
    "(Slip Opinion) "
  ],
  [
    -1,
    "OCTOBER TERM, 2012 1 Syllabus NOTE: Where it is feasible, a syllabus (headn..."
  ],
  [
    1,
    "             OCTOBER TERM, 2012                                       1\n\n ..."
  ],
  [
    0,
    "discrimination and its aftereffects have been extirpated.\u201d)."
  ]
```

It still does it with `inline_whitespace` instead of `all_whitespace`, and still does it when passing `checklines=False` to `diff_main`, so I'm not sure what's up. I imagine we could keep tweaking settings and get it to work, but since we're happy with the other lib I'm OK not figuring it out.

**Comment by mlissner** [comment]
> I imagine we could keep tweaking settings and get it to work, but since we're happy with the other lib I'm OK not figuring it out.

Sounds right to me.

**Comment by jcushman** [comment]
I think we can mark this fixed for now.

As an FYI, diffing is _still_ not particularly fast -- `annotate` ends up taking 20 times as long as `get_citations` on a typical CAP HTML document, but it can take a couple of seconds (1000x as long as `get_citations`) on particularly pathological examples. The instances where `annotate` takes a long time are the ones where a very long section was taken out by `clean_text` -- in our case that's ones with embedded images, so I might add special handling for that.

I don't have a generic elegant solution for this at the moment; I think to further speed up you need to exploit some knowledge of the texts, like with CAP's embedded img tags, OR find a way to make cleaners that are able to efficiently track the patches they make to avoid the need for a diffing step. I think we're in the realm of "fast enough" for now so I'm going to stop messing with it.

**Comment by mlissner** [comment]
Seems like at this point we're using C for both DMP and using CPU instructions in regex, so I don't imagine we can do much better without moving to assembly or something wild like that. Seems like it's fast enough to me — Thank you Jack!

**Comment by jcushman** [comment]
Yeah, just for future documentation, I think to make it faster we'd have to change the API a little bit, something like this:

```
cleaned_text, transforms = clean_text(orig_text, [...], get_transforms=True)
...
annotated_text = annotate(cleaned_text, annotations, transforms=transforms)
```

And then in cleaners.py you'd have `html(html_content: str, get_transforms=False) -> str, transforms:` that could (hypothetically) efficiently return a set of instructions (operational transforms) for turning the output back into the input. `annotate()` could then efficiently combine all of those with the annotations instead of needing to run a diff algorithm at all. (That's basically what diff_match_patch is doing for us -- laboriously reconstructing the set of operational transforms applied by `clean_text()`, so we don't have to write the cleaners themselves to keep track of them). 

That all sounds like too much work for now, e.g. it requires finding a streaming HTML parser that can generate the transforms and I don't know of one, but if we get to where speed is an issue it'd likely speed up annotation a great deal.
