### ISSUE TITLE
Use pin cite to filter out short cites in clustering

### ISSUE THREAD

**Issue by jcushman** [freelawproject/eyecite#74]
We can improve cite clustering by excluding short cites with implausible pin cites. Example:

"1 U.S. 200. blah blah. 2 We Missed This 20. blah blah. Id. at 22."

We'll currently cluster "Id. at 22" with "1 U.S. 200," but we could refuse on the basis that `int(id_cite.metadata.pin_cite) < int(us_cite.groups['page'])`. And then I think ignore the Id. cite entirely since it must be the product of some error or other.

**Comment by mlissner** [comment]
I guess we could figure out `MAX_OPINION_PAGE_COUNT` too and avoid something like:

> 1 U.S. 200 blah blah 1 U.S. 832

(Assuming we don't have any 632-page opinions.)

**Comment by jcushman** [comment]
CAP's very longest is 994 pages, but most cases are much shorter:

* 10th longest is 583 pages
* 100th longest is 230 pages
* 500th longest is 129 pages
* 1000th longest is 106 pages

So something like `MAX_OPINION_PAGE_COUNT = 150` might be reasonable, works for all but the longest 300 cases or so. Even if we end up being over-restrictive occasionally, I think there'd be big benefits for filtering false positives.

**Comment by mlissner** [comment]
Wow, What is that 994 page monster?

This all sounds good to me.

**Comment by jcushman** [comment]
Some of these are just data errors, but the longest real one looks like [United States v. Philip Morris USA, Inc](https://cite.case.law/f-supp-2d/449/1/). at 986 pages.

**Comment by mlissner** [comment]
Holy bejesus, y'all should get this into Lawvocado.

**Comment by devlux76** [comment]
I get that this was a judgment call, but I'd like to ask that the limit be reconsidered and rescinded. Longer rulings tend to be very influential and widely cited. US v. Phillip Morris & McConnell v. FEC are just a couple. If we're ignoring cites simply because the ruling is more than 150 pages then legal researchers lose a valuable tool. 

After all, one of the most important parts of Shepardizing is to look at how widely an opinion is cited and a 500 plus page ruling very likely touches on a lot of subjects; thus every pincite is vital in attempting to distinguish the finer points of law at play.

If there's an issue with pincites going off the deep end, for instance, page 850 of an 85 page ruling, we should look at the root cause and address that, rather than saying "Well it must be an error because it's greater than 1 std deviation."

Perhaps we could use this to flag it as suspect, but to filter it out completely just because it is improbable, would seem to me to be a disservice.  In fact it would be good to look at which opinions are > 1 std deviation in length and how widely cited they became. Something like that could be a valuable finding tool.

This MAX_OPINION_PAGE_COUNT variable, in its current incarnation, feels like the programmers equivalent of TLDR;
My opinion is that if the courts took 900+ pages to say what they felt needed to be said; we should honor their efforts by not discarding it.

**Comment by mlissner** [comment]
Here's my thoughts:

 - On the one hand, the limitation makes pin cites more accurate across millions of opinions
 - On the other hand, the limitation makes actual citations less accurate when they point to one of about 300 opinions

I think this means that I lean towards keeping the limitation at least until we can be confident that pin cites are working almost perfectly.

**Comment by devlux76** [comment]
I was planning on building a keycite replacement for my lawschool capstone anyways. Guess I should try to measure this pincite slippage somehow. I think I could whip something out that flags these pincites and checks to see if the page is within bounds. Is there any appetite for this though?

**Comment by mlissner** [comment]
Can you give an example of what you mean?
